version: '3.8'

services:
  wordpress:
    image: wordpress:latest
    platform: linux/amd64
    container_name: wordpress_skeleton
    restart: always
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
    volumes:
      - ./htdocs:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini

  db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: wordpress_skeleton_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./db_data:/var/lib/mysql
