services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress_skeleton
    restart: no
    ports:
      - "8081:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_user
      WORDPRESS_DB_PASSWORD: wordpress_password
      WORDPRESS_DB_NAME: wordpress_db
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_ENVIRONMENT_TYPE', 'local' );
    volumes:
      - ./htdocs:/var/www/html
      - ./php.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./dist/theme:/var/www/html/wp-content/themes/hoge
      - ./dist/plugins/hoge:/var/www/html/wp-content/plugins/hoge
      - ./dist/plugins/nunifuchisaka-custom-fields:/var/www/html/wp-content/plugins/nunifuchisaka-custom-fields
      - ./dist/plugins/ncf-test:/var/www/html/wp-content/plugins/ncf-test
      - ./dist/plugins/demo-styles:/var/www/html/wp-content/plugins/demo-styles
      - wp_default_theme_2025:/var/www/html/wp-content/themes/twentytwentyfive
      - wp_default_theme_2024:/var/www/html/wp-content/themes/twentytwentyfour
      - wp_default_theme_2023:/var/www/html/wp-content/themes/twentytwentythree
      - wp_default_plugin_akismet:/var/www/html/wp-content/plugins/akismet
      - wp_default_plugin_hello:/var/www/html/wp-content/plugins/hello.php
    depends_on:
      - db

  db:
    image: mariadb:10.6
    container_name: wordpress_skeleton_db
    restart: no
    environment:
      MYSQL_DATABASE: wordpress_db
      MYSQL_USER: wordpress_user
      MYSQL_PASSWORD: wordpress_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  wp_default_theme_2025:
  wp_default_theme_2024:
  wp_default_theme_2023:
  wp_default_plugin_akismet:
  wp_default_plugin_hello: